const CartActionType = {
  GET_CART_ITEM_START: "GET_CART_ITEM_START",
  GET_CART_ITEM_SUCCESS: "GET_CART_ITEM_SUCCESS",
  GET_CART_ITEM_FAILED: "GET_CART_ITEM_FAILED",
  //-----------------------------------------//
  ADD_ITEM_TO_CART_START: "ADD_ITEM_TO_CART_START",
  ADD_ITEM_TO_CART_SUCCESS: "ADD_ITEM_TO_CART_SUCCESS",
  ADD_ITEM_TO_CART_FAILED: "ADD_ITEM_TO_CART_FAILED",
  //-----------------------------------------//
  REMOVE_ITEM_TO_CART_START: "REMOVE_ITEM_TO_CART_START",
  REMOVE_ITEM_TO_CART_SUCCESS: "REMOVE_ITEM_TO_CART_SUCCESS",
  REMOVE_ITEM_TO_CART_FAILED: "REMOVE_ITEM_TO_CART_FAILED",
  //-----------------------------------------//
  SET_UPDATE_CART_ITEM_QUANTITY: "SET_UPDATE_CART_ITEM_QUANTITY",
  UPDATE_CART_ITEM_SUCCESS: "UPDATE_CART_ITEM_SUCCESS",
  UPDATE_CART_ITEM_FAILED: "UPDATE_CART_ITEM_FAILED",

  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_TO_CART: "REMOVE_ITEM_TO_CART",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  UPDATE_CART_ITEM_QUANTITY: "UPDATE_CART_ITEM_QUANTITY",
};

export default CartActionType;
