const ProductActionTypes = {
  GET_PRODUCTS_START: "GET_PRODUCTS_START",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  //---------
  SET_GET_PRODUCT_QUERY: "SET_GET_PRODUCT_QUERY",
};

export default ProductActionTypes;
