const ProductActionTypes = {
  GET_PRODUCTS_START: "GET_PRODUCTS_START",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  //---------
  SET_GET_PRODUCT_QUERY: "SET_GET_PRODUCT_QUERY",
  //---------
  SET_GET_PRODUCT_DETAILS_START: "SET_GET_PRODUCT_DETAILS",
  SET_GET_PRODUCT_DETAILS_SUCCESS: "SET_GET_PRODUCT_DETAILS_SUCCESS",
  SET_GET_PRODUCT_DETAILS_FAILED: "SET_GET_PRODUCT_DETAILS_FAILED",
  //---------
  SET_PRODUCT_SEARCH_QUERY: "SET_PRODUCT_SEARCH_QUERY",
};

export default ProductActionTypes;
