const WishlistActionTypes = {
  GET_WISHLIST_ITEMS_START: "GET_WISHLIST_ITEMS_START",
  GET_WISHLIST_ITEMS_SUCCESS: "GET_WISHLIST_ITEMS_SUCCESS",
  GET_WISHLIST_ITEMS_FAILED: "GET_WISHLIST_ITEMS_FAILED",
  //---------------
  ADD_WISHLIST_ITEM: "ADD_WISHLIST_ITEM",
  ADD_WISHLIST_ITEM_SUCCESS: "ADD_WISHLIST_ITEM_SUCCESS",
  ADD_WISHLIST_ITEM_FAILED: "ADD_WISHLIST_ITEM_FAILED",
  //---------------
  REMOVE_WISHLIST_ITEM: "REMOVE_WISHLIST_ITEM",
  REMOVE_WISHLIST_ITEM_SUCCESS: "REMOVE_WISHLIST_ITEM_SUCCESS",
  REMOVE_WISHLIST_ITEM_FAILED: "REMOVE_WISHLIST_ITEM_FAILED",
};

export default WishlistActionTypes;
